### ISSUE TITLE
Mod Not working

### ISSUE THREAD

**Issue by BuckTheWeasel** [Darkhax-Minecraft/Modded-Debug-WorldType#1]
Hello

I have Installed you mod but it not working at all.
It loaded but when i want to select it on worldtype it not there :/

minecraft 1.12.2
Minecraft Forge : 14.23.5.2836
Mod version : ModDebugWorldType-1.12.2-1.0.2
API Version : Bookshelf-1.12.2-2.3.577

**Comment by Darkhax** [comment]
The world type is a vanilla feature. If it's not showing up you may be accessing it incorrectly (you need to hold down shift) or another mod may be removing it.
